### PR TITLE
Added CONFIG_NO_STD_RELOC: Avoids tiny section -> Fixes linking-time …

### PR DESCRIPTION
**Pull request by NBruschi**
This patch disables tiny section relocation which confuses the linker and generates a linking-time error when there is -flto (LDFLAG)

### CODE REVIEW

**Review by FrancescoConti — APPROVED** [review]
Given the strong impact on performance if `-flto` cannot be enabled, two thumbs up for me 👍 👍

**Comment by gautschimi** [comment]
is this a fix for -flto or just a workaround?

**Comment by NBruschi** [comment]
it should be a fix, which means that, if you don’t define CONFIG_NO_STD_RELOC, you don’t use assembly code optimizations that broke the -flto.

**Comment by FrancescoConti** [comment]
From the discussion we had in the morning with @gtagliavini , it looks to me that the current behavior provides some benefit in very fine-grain cases (e.g., calling a runtime function requires 1 instruction less), but prevents `-flto`. For realistic benchmarks (https://github.com/pulp-platform/dory_examples) we have 15-20% performance improvement with this change.
So I think that the `CONFIG_NO_STD_RELOC` define can be useful for micro-benchmarks, but should be disabled by default.

**Comment by gautschimi** [comment]
I think you don't need the define. just use the version that works with -flto. the few additional instructions are negligible.

but as far as I understand its more a problem in the toolchain that cannot handle these assembly constructs. -> this is more a workaround than a fix.

**Comment by NBruschi** [comment]
The next step will be improving the toolchain to properly support that structure. We are planning how and when to change it, and will likely do so in a future release. Until then, in order not to compromise compatibility with other versions, I have added a definition which is locked by default. If someone has a version of the toolchain that supports that construct, they might use more optimized runtime routine calls, triggering them during the building process.
Moreover, I think it is useful for small synthetic benchmarks that take considerable benefits from the fine-grain optimization of runtime functions, and by removing those parts, they won't be evaluable.

**Review by gtagliavini — APPROVED** [review]

**Pull request merged**
