### PR TITLE
Timer unit dev

### PR DESCRIPTION
**Pull request by florent-gwt**
I added timer unit testcase + some few macro & func in archi / hal.
Also some fixes in vega properties.h

### CODE REVIEW

**Comment by haugoug** [comment]
This seems to break other chips: https://iis-jenkins.ee.ethz.ch/job/pulp-sdk-centos7/816/

**Comment by florent-gwt** [comment]
Shall i merge it into integration or vega branch finally ?

**Comment by florent-gwt** [comment]
Shall i merge it into integration or vega branch finally ?

**Comment by haugoug** [comment]
in integration

**Comment by haugoug** [comment]
This has already been updated

**Pull request closed without merging**
